<?xml version="1.0" encoding="UTF-8"?>
<project name="BackpackHero" default="jar" basedir=".">

    <!-- Compilation -->
    <target name="compile">
        <mkdir dir="classes"/>
        <javac srcdir="src" destdir="classes" includeantruntime="false">
            <classpath>
                <fileset dir="lib" includes="*.jar"/>
            </classpath>
        </javac>
    </target>

    <!-- JAR exécutable -->
    <target name="jar" depends="compile">
        <jar destfile="BackpackHero.jar" basedir="classes">
            <manifest>
                <attribute name="Main-Class" value="game.GameController"/>
            </manifest>
            <zipgroupfileset dir="lib" includes="*.jar"/>
        </jar>
    </target>

    <!-- Javadoc -->
    <target name="javadoc">
        <mkdir dir="docs/doc"/>
        <javadoc sourcepath="src" destdir="docs/doc" use="true"
                 windowtitle="BackpackHero Javadoc" docencoding="UTF-8" encoding="UTF-8" locale="en">
            <classpath>
                <fileset dir="lib" includes="*.jar"/>
            </classpath>
        </javadoc>
    </target>

    <!-- Nettoyage -->
    <target name="clean">
        <delete dir="classes"/>
        <delete file="BackpackHero.jar"/>
        <delete dir="docs/doc"/>
    </target>

</project>